# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod_lat', models.CharField(max_length=30, verbose_name='Rod latinsky')),
                ('druh_lat', models.CharField(blank=True, max_length=30, verbose_name='Druh latinsky')),
                ('kultivar', models.CharField(blank=True, max_length=30, verbose_name='Kultivar')),
                ('rod_sk', models.CharField(blank=True, default='neuvedene', max_length=30, verbose_name='Rod slovensky')),
                ('druh_sk', models.CharField(blank=True, default='neuvedene', max_length=30, verbose_name='Druh slovensky')),
                ('typ', models.CharField(blank=True, choices=[('1', 'Trvalka'), ('2', 'Cibulovina'), ('3', 'Trava'), ('4', 'Ker'), ('5', 'Popinavy ker'), ('6', 'Popinavka'), ('7', 'Strom')], max_length=1, verbose_name='Typ')),
                ('vyska', models.FloatField(blank=True, null=True, verbose_name='Vyska [m]')),
                ('rozpon', models.IntegerField(blank=True, null=True, verbose_name='Rozpon')),
                ('farba', models.CharField(blank=True, choices=[('1', 'Biela'), ('2', 'Zlta'), ('3', 'Oranzova'), ('4', 'Cervena'), ('5', 'Ruzova'), ('6', 'Fialova'), ('7', 'Zelena'), ('8', 'Modra'), ('9', 'Hneda')], max_length=1, null=True, verbose_name='Farba')),
                ('pouzitie', models.CharField(blank=True, choices=[('1', 'Vypln'), ('2', 'Kostra'), ('3', 'Dominanta'), ('4', 'Formalna vysadba'), ('5', 'Neformalna vysadba'), ('6', 'Podrast'), ('7', 'Podopokryvna'), ('8', 'Soliter'), ('9', 'Zivy plot')], max_length=1, null=True, verbose_name='Pouzitie')),
                ('kvitnutie_od', models.CharField(blank=True, choices=[('1', 'Januar'), ('2', 'Februar'), ('3', 'Marec'), ('4', 'April'), ('5', 'Maj'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'August'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'December')], max_length=2, null=True, verbose_name='Kvitnutie od')),
                ('kvitnutie_do', models.CharField(blank=True, choices=[('1', 'Januar'), ('2', 'Februar'), ('3', 'Marec'), ('4', 'April'), ('5', 'Maj'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'August'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'December')], max_length=2, null=True, verbose_name='Kvitnutie do')),
                ('stanovisko', models.CharField(blank=True, choices=[('1', 'Volna plocha'), ('2', 'Porast'), ('3', 'Okraje porastov'), ('4', 'Zahon'), ('5', 'Kamenista vysadba'), ('6', 'Alpinium'), ('7', 'Okraje vod'), ('8', 'Voda'), ('9', 'Travy')], max_length=1, null=True, verbose_name='Stanovisko')),
                ('slnko', models.CharField(blank=True, choices=[('1', 'Priame slnko'), ('2', 'Polotien'), ('3', 'Tien'), ('4', 'Chulostive na mraz'), ('5', 'Nezalezi')], max_length=1, null=True, verbose_name='Slnko')),
                ('vlaha', models.CharField(blank=True, choices=[('1', 'Suche stanoviste'), ('2', 'Pravidelna zavlaha'), ('3', 'Dostatok vlahy')], max_length=1, null=True, verbose_name='Vlaha')),
                ('fotka', models.ImageField(blank=True, null=True, upload_to='')),
                ('poznamka', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
