# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='typ',
            field=models.CharField(blank=True, choices=[('1', 'Trvalka'), ('2', 'Cibulovina'), ('3', 'Trava'), ('4', 'Ker'), ('5', 'Popinavy ker'), ('6', 'Popinavka'), ('7', 'Strom')], max_length=1, null=True, verbose_name='Typ'),
        ),
    ]
